### ISSUE TITLE
requirements.txt is missing

### ISSUE THREAD

**Issue by PySchilling** [FlUxIuS/V2GInjector#1]
Hello,

It seems that there is missing a file: requirements.txt to install python dependencies.
Could you please add it?

Thanks,
Volker

**Comment by FlUxIuS** [comment]
Done on the last commit! Can you check if everything is alright in your side?

Thanks in advance!

**Comment by PySchilling** [comment]
Hello Mr. Dudek,

thenks for the requirements.txt.

Is it possible to get some schematik how to connect the plc to the ev 
or the charging station?
We wonder how the IEC 61851 and the PWM Signaling is done!

Thanks,
Volker schilling

Am Sa, 30. Mai, 2020 um 6:31 NACHMITTAGS schrieb Sébastien Dudek 
<notifications@github.com>:

**Comment by PySchilling** [comment]
Hello Mr. Dudek,

is it possible that you share us some details about how to connect the 
hardware?

Best regards,
Volker


Am Sa, 30. Mai, 2020 um 6:31 NACHMITTAGS schrieb Sébastien Dudek 
<notifications@github.com>:

**Comment by moliza** [comment]
> Bonjour,
> 
> Il semble qu'il manque un fichier: requirements.txt pour installer les dépendances python.
> Pourriez-vous s'il vous plaît l'ajouter?
> 
> Merci,
> Volker

Hello Volker,

I had Sebastien online, the file was submitted by him. (I thank him by the way,)
If you have problems to go further I invite you to perform these commands:
git submodule update --init --recursive
or pip freeze > requirements.txt
If error  network...
pip install configparser
If  error libs.fonts
sudo easy_install -U colorama

Good luck !

**Comment by FlUxIuS** [comment]
> Hello Mr. Dudek, is it possible that you share us some details about how to connect the hardware? Best regards, Volker Am Sa, 30. Mai, 2020 um 6:31 NACHMITTAGS schrieb Sébastien Dudek <notifications@github.com>:
> […](#)
> Done on the last commit! Can you check if everything is alright in your side? Thanks in advance! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi sure! 

What type of hardware do you have?
