### ISSUE TITLE
Devolo 1200+ modification

### ISSUE THREAD

**Issue by tomarigr** [FlUxIuS/V2GInjector#3]
Hi, can you share some details about how the Devolo 1200+  device must be modified to be connected to the CP and PE lines? 

Thanks
Thomas

**Comment by FlUxIuS** [comment]
This will be in my stack of todo for this project. I'll try to better illustrate the setup if I have time. This modification is not easy as modifying an old HomePlugAV device before the modulation&demod.

**Comment by FlUxIuS** [comment]
There are some smaller kits for QCA 7k that can be bough in markets that can really do the job without having to hook on TR1+ and TR1-
