### ISSUE TITLE
Scapy and HomeplugAV module

### ISSUE THREAD

**Issue by dme8a8** [FlUxIuS/V2GInjector#6]
How to read the PIB file with ModulePIB()?

Can you please provide an example?

All I get are
`<code>`
... last 2 frames repeated, from the frame below ...

/Library/Python/3.8/site-packages/scapy/packet.py in __getattr__(self, attr)
    370     def __getattr__(self, attr):
    371         try:
--> 372             fld, v = self.getfield_and_val(attr)
    373         except TypeError:
    374             return self.payload.__getattr__(attr)

RecursionError: maximum recursion depth exceeded
`</code>`

**Comment by FlUxIuS** [comment]
Hi,

Can you provide a PIB dump so I can check an fix if there is an issue with your file?

Thank you in advance!

Cheers

**Comment by dme8a8** [comment]
Hi,

Unfortunately that is not possible. The file is copyrighted.


But maybe you can provide the commands you use to load a pib file?

**Comment by FlUxIuS** [comment]
Still not having any samples to fix it, but the issue should go on HomePlugPWN project rather than V2GInjector.

ModulePIB should be readapted to new QCA modules, and probably some reverse will have to be made on these to get all fields
