### ISSUE TITLE
Promiscuous mode for PLC HW

### ISSUE THREAD

**Issue by SebaLukas** [FlUxIuS/V2GInjector#8]
Hi,

I have a problem to sniff the V2G messages.
I can join the AVLN network and I also see the SECC request message from the EV. But that's it.

In your research paper you wrote that the PLC kit can be set in a promiscuous mode to receive all messages. (Chapter 5.8) 
How can I set this mode?
For your information: I use the dLAN Green PHY eval board EU II. 

Thanks in advance
Sebastian

**Comment by dme8a8** [comment]
Did you manage to work out how?

**Comment by FlUxIuS** [comment]
Hey,

Sorry for the late reply => busy beginning of the year!

So if I remember correctly on this precise kit, the bridge is made on the LPC side so you need to modify it a bit the firmware to capture the QCA Ethernet interface without filters.

If you want something in pure software, there is still the possibility to abuse the IPv6 NDP, or try to race the SECC discovery (which could be hard, but there are some tricks to trying to DoS the V2G client).

Or there is also an ultimate way using 2 PLC communicating together on host interface, to actually make a hardware Man-In-The-Middle attack, which gives you also a nice control over the packets sent on the two sides.

**Comment by SebaLukas** [comment]
Thank you for your message. That really helps me.

**Comment by FlUxIuS** [comment]
No problem :)!
